#!/usr/bin/env python3
"""
Collect 5mer context counts from processed count files.

This script uses the count files generated by collect_mutation_counts.py to efficiently
collect 5mer context counts for strand-collapsed mutation bias analysis. It captures
both C>T and G>A mutations by converting G>A mutations to their C>T equivalent via
reverse complement, ensuring all mutations are represented as C-centered 5mers.

Inputs:
- Directory of .counts files (from collect_mutation_counts.py)
- Reference genome FASTA file
- GFF annotation file for gene coordinates
- Optional exclusion mask file

Outputs:
- Per-sample 5mer context counts (JSON format) with total, gene, and intergenic counts
- Summary statistics
"""
import argparse
import glob
import os
import json
import pandas as pd
from collections import defaultdict, Counter
import multiprocessing as mp
from functools import partial
import gzip


def load_genome_sequence(genome_fasta):
    """Load genome sequence from FASTA file (supports both regular and gzipped files)."""
    genome_seq = ""
    
    # Check if file is gzipped
    if genome_fasta.endswith('.gz'):
        with gzip.open(genome_fasta, 'rt') as f:
            for line in f:
                if not line.startswith('>'):
                    genome_seq += line.strip().upper()
    else:
        with open(genome_fasta, 'r') as f:
            for line in f:
                if not line.startswith('>'):
                    genome_seq += line.strip().upper()
    
    return genome_seq




def load_exclusion_mask(mask_file):
    """Load exclusion mask from file."""
    excluded_sites = set()
    with open(mask_file) as f:
        header = next(f, None)  # Skip header
        for line in f:
            chrom, pos = line.strip().split('\t')
            excluded_sites.add((chrom, pos))
    return excluded_sites


def load_gene_coordinates(gff_file):
    """Load gene coordinates from GFF file."""
    gene_coords = []
    
    with open(gff_file, 'r') as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            
            fields = line.strip().split('\t')
            if len(fields) < 9:
                continue
                
            chrom, source, feature_type, start, end, score, strand, phase, attributes = fields
            
            # Only consider gene features
            if feature_type == 'gene':
                gene_coords.append((chrom, int(start), int(end)))
    
    return gene_coords


def is_position_in_gene(chrom, pos, gene_coords):
    """Check if a position is within any gene."""
    pos_int = int(pos)
    for gene_chrom, gene_start, gene_end in gene_coords:
        if gene_chrom == chrom and gene_start <= pos_int <= gene_end:
            return True
    return False


def reverse_complement(seq):
    """Get reverse complement of a DNA sequence."""
    complement = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C', 'N': 'N'}
    return ''.join(complement[base] for base in reversed(seq))


def get_5mer_context(genome_seq, chrom, pos, kmer_size=5):
    """Get 5mer context around a position in the genome."""
    try:
        pos_idx = int(pos) - 1  # Convert to 0-based
        flank = kmer_size // 2
        
        # Check bounds
        if pos_idx - flank < 0 or pos_idx + flank >= len(genome_seq):
            return None
            
        kmer = genome_seq[pos_idx - flank:pos_idx + flank + 1]
        if len(kmer) != kmer_size:
            return None
            
        return kmer
    except (ValueError, IndexError):
        return None


def process_count_file(args_tuple):
    """Process a single count file to extract 5mer contexts."""
    count_file, genome_seq, excluded_sites, min_alt, output_dir, gene_coords, no_strand_collapse = args_tuple
    
    try:
        kmer_counts = defaultdict(int)
        gene_kmer_counts = defaultdict(int)
        intergenic_kmer_counts = defaultdict(int)
        
        # For non-strand-collapsed mode, separate C and G centered counts
        if no_strand_collapse:
            c_kmer_counts = defaultdict(int)
            g_kmer_counts = defaultdict(int)
            c_gene_kmer_counts = defaultdict(int)
            c_intergenic_kmer_counts = defaultdict(int)
            g_gene_kmer_counts = defaultdict(int)
            g_intergenic_kmer_counts = defaultdict(int)
        
        total_sites = 0
        c_sites = 0
        mutated_sites = 0
        gene_mutated_sites = 0
        intergenic_mutated_sites = 0
        
        with open(count_file, 'r') as f:
            header = next(f, None)  # Skip header
            for line in f:
                fields = line.strip().split('\t')
                if len(fields) < 9:
                    continue
                    
                chrom, pos, ref, ref_count, A_count, C_count, G_count, T_count, depth = fields
                
                # Convert to int
                ref_count = int(ref_count)
                depth = int(depth)
                total_sites += 1
                
                # Only consider C or G sites (strand collapsed)
                if ref not in ['C', 'G']:
                    continue
                    
                c_sites += 1
                
                # Apply exclusion mask if provided
                if excluded_sites and (chrom, pos) in excluded_sites:
                    continue
                
                # Check for EMS mutations
                if ref == 'C':
                    # C>T mutation
                    t_count = int(T_count)
                    if t_count >= min_alt:
                        kmer = get_5mer_context(genome_seq, chrom, pos)
                        if kmer and kmer[2] == 'C':
                            mutated_sites += 1
                            
                            if no_strand_collapse:
                                # Store C-centered 5mer
                                c_kmer_counts[kmer] += 1
                                if is_position_in_gene(chrom, pos, gene_coords):
                                    c_gene_kmer_counts[kmer] += 1
                                    gene_mutated_sites += 1
                                else:
                                    c_intergenic_kmer_counts[kmer] += 1
                                    intergenic_mutated_sites += 1
                            else:
                                # Strand collapsed mode
                                kmer_counts[kmer] += 1
                                if is_position_in_gene(chrom, pos, gene_coords):
                                    gene_kmer_counts[kmer] += 1
                                    gene_mutated_sites += 1
                                else:
                                    intergenic_kmer_counts[kmer] += 1
                                    intergenic_mutated_sites += 1
                        
                elif ref == 'G':
                    # G>A mutation
                    a_count = int(A_count)
                    if a_count >= min_alt:
                        kmer = get_5mer_context(genome_seq, chrom, pos)
                        if kmer and kmer[2] == 'G':
                            mutated_sites += 1
                            
                            if no_strand_collapse:
                                # Store G-centered 5mer
                                g_kmer_counts[kmer] += 1
                                if is_position_in_gene(chrom, pos, gene_coords):
                                    g_gene_kmer_counts[kmer] += 1
                                    gene_mutated_sites += 1
                                else:
                                    g_intergenic_kmer_counts[kmer] += 1
                                    intergenic_mutated_sites += 1
                            else:
                                # Strand collapsed mode - convert to C>T equivalent
                                kmer_rc = reverse_complement(kmer)
                                if kmer_rc and kmer_rc[2] == 'C':
                                    kmer_counts[kmer_rc] += 1
                                    if is_position_in_gene(chrom, pos, gene_coords):
                                        gene_kmer_counts[kmer_rc] += 1
                                        gene_mutated_sites += 1
                                    else:
                                        intergenic_kmer_counts[kmer_rc] += 1
                                        intergenic_mutated_sites += 1
        
        # Write 5mer context counts to JSON file
        basename = os.path.basename(count_file)
        output_file = os.path.join(output_dir, basename.replace('.counts', '_5mer_contexts.json'))
        
        # Create combined output with all counts
        if no_strand_collapse:
            output_data = {
                'c_centered': {
                    'total': dict(c_kmer_counts),
                    'gene': dict(c_gene_kmer_counts),
                    'intergenic': dict(c_intergenic_kmer_counts)
                },
                'g_centered': {
                    'total': dict(g_kmer_counts),
                    'gene': dict(g_gene_kmer_counts),
                    'intergenic': dict(g_intergenic_kmer_counts)
                }
            }
        else:
            output_data = {
                'total': dict(kmer_counts),
                'gene': dict(gene_kmer_counts),
                'intergenic': dict(intergenic_kmer_counts)
            }
        
        with open(output_file, 'w') as f:
            json.dump(output_data, f, indent=2)
        
        if no_strand_collapse:
            return {
                'file': basename,
                'success': True,
                'total_sites': total_sites,
                'c_sites': c_sites,
                'mutated_sites': mutated_sites,
                'gene_mutated_sites': gene_mutated_sites,
                'intergenic_mutated_sites': intergenic_mutated_sites,
                'unique_c_5mers': len(c_kmer_counts),
                'unique_g_5mers': len(g_kmer_counts),
                'total_c_5mer_counts': sum(c_kmer_counts.values()),
                'total_g_5mer_counts': sum(g_kmer_counts.values()),
                'gene_c_5mer_counts': sum(c_gene_kmer_counts.values()),
                'gene_g_5mer_counts': sum(g_gene_kmer_counts.values()),
                'intergenic_c_5mer_counts': sum(c_intergenic_kmer_counts.values()),
                'intergenic_g_5mer_counts': sum(g_intergenic_kmer_counts.values())
            }
        else:
            return {
                'file': basename,
                'success': True,
                'total_sites': total_sites,
                'c_sites': c_sites,
                'mutated_sites': mutated_sites,
                'gene_mutated_sites': gene_mutated_sites,
                'intergenic_mutated_sites': intergenic_mutated_sites,
                'unique_5mers': len(kmer_counts),
                'total_5mer_counts': sum(kmer_counts.values()),
                'gene_5mer_counts': sum(gene_kmer_counts.values()),
                'intergenic_5mer_counts': sum(intergenic_kmer_counts.values())
            }
        
    except Exception as e:
        return {
            'file': os.path.basename(count_file),
            'success': False,
            'error': str(e)
        }


def main():
    parser = argparse.ArgumentParser(
        description="Collect 5mer context counts from processed count files"
    )
    parser.add_argument("--counts-dir", required=True,
                        help="Directory containing .counts files")
    parser.add_argument("--output-dir", required=True,
                        help="Output directory for 5mer context files")
    parser.add_argument("--genome-fasta", required=True,
                        help="Path to reference genome FASTA file (supports .gz files)")
    parser.add_argument("--gff-file", required=True,
                        help="Path to GFF annotation file for gene coordinates")
    parser.add_argument("--exclusion-mask", type=str, default=None,
                        help="Path to exclusion mask file (optional)")
    parser.add_argument("--min-alt", type=int, default=3,
                        help="Minimum alt allele count for EMS mutations (default 3)")
    parser.add_argument("--n-processes", type=int, default=None,
                        help="Number of processes to use (default: number of CPUs)")
    parser.add_argument("--no-strand-collapse", action="store_true",
                        help="Do not strand collapse - collect both C-centered and G-centered 5mers separately")
    args = parser.parse_args()

    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)
    
    # Load genome sequence
    print(f"Loading genome sequence from {args.genome_fasta}")
    genome_seq = load_genome_sequence(args.genome_fasta)
    print(f"Loaded genome sequence of length {len(genome_seq):,}")
    
    # Load gene coordinates
    print(f"Loading gene coordinates from {args.gff_file}")
    gene_coords = load_gene_coordinates(args.gff_file)
    print(f"Loaded {len(gene_coords)} gene coordinates")
    
    # Load exclusion mask if provided
    excluded_sites = None
    if args.exclusion_mask:
        if os.path.exists(args.exclusion_mask):
            excluded_sites = load_exclusion_mask(args.exclusion_mask)
            print(f"Loaded exclusion mask: {len(excluded_sites):,} sites to exclude")
        else:
            print(f"Warning: Exclusion mask file not found: {args.exclusion_mask}")
    
    # Find all count files
    count_files = glob.glob(os.path.join(args.counts_dir, "*.counts"))
    if not count_files:
        print(f"No .counts files found in {args.counts_dir}")
        return
    
    print(f"Found {len(count_files)} count files")
    
    # Prepare arguments for multiprocessing
    process_args = []
    for count_file in count_files:
        process_args.append((count_file, genome_seq, excluded_sites, args.min_alt, args.output_dir, gene_coords, args.no_strand_collapse))
    
    # Process files in parallel
    if args.n_processes:
        n_processes = args.n_processes
    elif mp.cpu_count() > len(count_files):
        n_processes = len(count_files)
    else:
        n_processes = mp.cpu_count()
    
    print(f"Processing {len(count_files)} files using {n_processes} processes")
    
    with mp.Pool(n_processes) as pool:
        results = pool.map(process_count_file, process_args)
    
    # Report results
    successful = [r for r in results if r['success']]
    failed = [r for r in results if not r['success']]
    
    print(f"\n=== PROCESSING COMPLETE ===")
    print(f"Successfully processed: {len(successful)} files")
    print(f"Failed: {len(failed)} files")
    
    if successful:
        total_sites = sum(r['total_sites'] for r in successful)
        total_c_sites = sum(r['c_sites'] for r in successful)
        total_mutated = sum(r['mutated_sites'] for r in successful)
        
        if args.no_strand_collapse:
            total_c_5mers = sum(r.get('unique_c_5mers', 0) for r in successful)
            total_g_5mers = sum(r.get('unique_g_5mers', 0) for r in successful)
            total_c_5mer_counts = sum(r.get('total_c_5mer_counts', 0) for r in successful)
            total_g_5mer_counts = sum(r.get('total_g_5mer_counts', 0) for r in successful)
        else:
            total_5mers = sum(r.get('unique_5mers', 0) for r in successful)
            total_5mer_counts = sum(r.get('total_5mer_counts', 0) for r in successful)
        
        print(f"\n=== SUMMARY STATISTICS ===")
        print(f"Total sites processed: {total_sites:,}")
        print(f"C/G sites (strand collapsed): {total_c_sites:,}")
        print(f"Mutated sites (C>T or G>A, ≥{args.min_alt} alt alleles): {total_mutated:,}")
        print(f"  - Gene mutations: {sum(r['gene_mutated_sites'] for r in successful):,}")
        print(f"  - Intergenic mutations: {sum(r['intergenic_mutated_sites'] for r in successful):,}")
        
        if args.no_strand_collapse:
            print(f"Unique C-centered 5mer contexts: {sum(r.get('unique_c_5mers', 0) for r in successful):,}")
            print(f"Unique G-centered 5mer contexts: {sum(r.get('unique_g_5mers', 0) for r in successful):,}")
            print(f"Total C-centered 5mer counts: {sum(r.get('total_c_5mer_counts', 0) for r in successful):,}")
            print(f"Total G-centered 5mer counts: {sum(r.get('total_g_5mer_counts', 0) for r in successful):,}")
            print(f"  - Gene C-centered 5mer counts: {sum(r.get('gene_c_5mer_counts', 0) for r in successful):,}")
            print(f"  - Gene G-centered 5mer counts: {sum(r.get('gene_g_5mer_counts', 0) for r in successful):,}")
            print(f"  - Intergenic C-centered 5mer counts: {sum(r.get('intergenic_c_5mer_counts', 0) for r in successful):,}")
            print(f"  - Intergenic G-centered 5mer counts: {sum(r.get('intergenic_g_5mer_counts', 0) for r in successful):,}")
        else:
            print(f"Unique 5mer contexts: {total_5mers:,}")
            print(f"Total 5mer counts: {total_5mer_counts:,}")
            print(f"  - Gene 5mer counts: {sum(r['gene_5mer_counts'] for r in successful):,}")
            print(f"  - Intergenic 5mer counts: {sum(r['intergenic_5mer_counts'] for r in successful):,}")
        
        # Create summary table
        summary_data = []
        for result in successful:
            if args.no_strand_collapse:
                summary_data.append({
                    'sample': result['file'].replace('.counts', ''),
                    'total_sites': result['total_sites'],
                    'c_sites': result['c_sites'],
                    'mutated_sites': result['mutated_sites'],
                    'gene_mutated_sites': result['gene_mutated_sites'],
                    'intergenic_mutated_sites': result['intergenic_mutated_sites'],
                    'unique_c_5mers': result.get('unique_c_5mers', 0),
                    'unique_g_5mers': result.get('unique_g_5mers', 0),
                    'total_c_5mer_counts': result.get('total_c_5mer_counts', 0),
                    'total_g_5mer_counts': result.get('total_g_5mer_counts', 0),
                    'gene_c_5mer_counts': result.get('gene_c_5mer_counts', 0),
                    'gene_g_5mer_counts': result.get('gene_g_5mer_counts', 0),
                    'intergenic_c_5mer_counts': result.get('intergenic_c_5mer_counts', 0),
                    'intergenic_g_5mer_counts': result.get('intergenic_g_5mer_counts', 0)
                })
            else:
                summary_data.append({
                    'sample': result['file'].replace('.counts', ''),
                    'total_sites': result['total_sites'],
                    'c_sites': result['c_sites'],
                    'mutated_sites': result['mutated_sites'],
                    'gene_mutated_sites': result['gene_mutated_sites'],
                    'intergenic_mutated_sites': result['intergenic_mutated_sites'],
                    'unique_5mers': result.get('unique_5mers', 0),
                    'total_5mer_counts': result.get('total_5mer_counts', 0),
                    'gene_5mer_counts': result.get('gene_5mer_counts', 0),
                    'intergenic_5mer_counts': result.get('intergenic_5mer_counts', 0)
                })
        
        summary_df = pd.DataFrame(summary_data)
        summary_file = os.path.join(args.output_dir, '5mer_context_summary.tsv')
        summary_df.to_csv(summary_file, sep='\t', index=False)
        print(f"\nSummary table saved to: {summary_file}")
    
    if failed:
        print(f"\nFailed files:")
        for result in failed:
            print(f"  {result['file']}: {result['error']}")
    
    print(f"\nOutput files written to: {args.output_dir}")


if __name__ == "__main__":
    main()
